// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class 0004OrdersStatusUpdateOrderAssignTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void 0004OrdersStatusUpdateOrderAssign() {
    driver.get("http://10.5.0.145:3000//login");
    driver.manage().window().setSize(new Dimension(1280, 672));
    driver.findElement(By.id(":r0:")).click();
    driver.findElement(By.id(":r0:")).sendKeys("admin@gmail.com");
    driver.findElement(By.id(":r1:")).click();
    driver.findElement(By.id(":r1:")).sendKeys("Admin@0426#user");
    driver.findElement(By.cssSelector(".MuiButton-root")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(2) .MuiTypography-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".Mui-selected"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("order-status-677fd28c84c2ef5caa011d7d")).click();
    {
      WebElement dropdown = driver.findElement(By.id("order-status-677fd28c84c2ef5caa011d7d"));
      dropdown.findElement(By.xpath("//option[. = 'PayFailed']")).click();
    }
    driver.findElement(By.id("order-status-674d610a52719623389622d0")).click();
    {
      WebElement dropdown = driver.findElement(By.id("order-status-674d610a52719623389622d0"));
      dropdown.findElement(By.xpath("//option[. = 'PaySuccess']")).click();
    }
    driver.findElement(By.id("order-status-677fd8f484c2ef5caa011d80")).click();
    {
      WebElement dropdown = driver.findElement(By.id("order-status-677fd8f484c2ef5caa011d80"));
      dropdown.findElement(By.xpath("//option[. = 'PaySuccess']")).click();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(8)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("order-status-6780f975bda0445bb37a241c")).click();
    {
      WebElement dropdown = driver.findElement(By.id("order-status-6780f975bda0445bb37a241c"));
      dropdown.findElement(By.xpath("//option[. = 'Paid']")).click();
    }
    driver.findElement(By.id("order-status-677fd75b84c2ef5caa011d7f")).click();
    {
      WebElement dropdown = driver.findElement(By.id("order-status-677fd75b84c2ef5caa011d7f"));
      dropdown.findElement(By.xpath("//option[. = 'Accepted']")).click();
    }
    driver.findElement(By.id("order-status-674ab1b6a32970e259ed5ef1")).click();
    {
      WebElement dropdown = driver.findElement(By.id("order-status-674ab1b6a32970e259ed5ef1"));
      dropdown.findElement(By.xpath("//option[. = 'Ready']")).click();
    }
    driver.findElement(By.id("order-status-677fd3eb84c2ef5caa011d7e")).click();
    {
      WebElement dropdown = driver.findElement(By.id("order-status-677fd3eb84c2ef5caa011d7e"));
      dropdown.findElement(By.xpath("//option[. = 'Collected']")).click();
    }
    driver.findElement(By.id("order-status-674ad8cca32970e259ed5ef4")).click();
    {
      WebElement dropdown = driver.findElement(By.id("order-status-674ad8cca32970e259ed5ef4"));
      dropdown.findElement(By.xpath("//option[. = 'Completed']")).click();
    }
    driver.findElement(By.id("order-status-67810855bda0445bb37a241d")).click();
    {
      WebElement dropdown = driver.findElement(By.id("order-status-67810855bda0445bb37a241d"));
      dropdown.findElement(By.xpath("//option[. = 'Cancelled']")).click();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiTableContainer-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiTableContainer-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiTableContainer-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".MuiTableRow-root:nth-child(7) > .MuiTableCell-root:nth-child(11) svg")).click();
    driver.findElement(By.cssSelector(".MuiPaper-root:nth-child(3) > .MuiPaper-root:nth-child(2) .MuiButtonBase-root")).click();
    driver.findElement(By.cssSelector(".css-138zggh-MuiButtonBase-root-MuiButton-root")).click();
    js.executeScript("window.scrollTo(0,221.3333282470703)");
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(1) .MuiTypography-root")).click();
    driver.findElement(By.cssSelector(".MuiIconButton-edgeEnd")).click();
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(2) > .MuiBox-root")).click();
    driver.close();
  }
}
