// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class 0007SettingsInviteUserPermissionsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void 0007SettingsInviteUserPermissions() {
    driver.get("http://10.5.0.145:3000/login");
    driver.manage().window().setSize(new Dimension(1296, 688));
    driver.findElement(By.id(":r0:")).click();
    driver.findElement(By.id(":r0:")).sendKeys("admin@gmail.com");
    driver.findElement(By.id(":r1:")).click();
    driver.findElement(By.id(":r1:")).sendKeys("Admin@0426#user");
    driver.findElement(By.cssSelector(".MuiButton-root")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(7) .MuiTypography-root")).click();
    driver.findElement(By.cssSelector(".MuiGrid-root:nth-child(1) > .MuiPaper-root > .MuiTypography-root")).click();
    driver.findElement(By.cssSelector(".MuiButton-contained-dark")).click();
    driver.findElement(By.id(":rf:")).click();
    vars.put("randomEmail", js.executeScript("return \"user\" + Math.floor(Math.random() * 100000 ) + \"@example.com\" ;"));
    driver.findElement(By.xpath("//input[@id=\':rf:\']")).sendKeys(vars.get("randomEmail").toString());
    driver.findElement(By.id(":rg:")).click();
    vars.put("randomName", js.executeScript("return \"Name\" + Math.floor (Math.random () * 10000 ) ;"));
    driver.findElement(By.xpath("//input[@id=\':rg:\']")).sendKeys(vars.get("randomName").toString());
    driver.findElement(By.cssSelector(".MuiFormControlLabel-root:nth-child(8) .PrivateSwitchBase-input")).click();
    driver.findElement(By.cssSelector(".css-138zggh-MuiButtonBase-root-MuiButton-root")).click();
    driver.findElement(By.cssSelector(".css-1qtpij-MuiTypography-root")).click();
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(2) > .MuiBox-root")).click();
    driver.close();
  }
}
